# Welcome to Jekyll!
#
title: Forrestry Jekyll Demo
description: >- # this means to ignore newlines until "baseurl:"
  This is a demo for a docs site we're working on. We are trying out several
  platforms to see what feels right
baseurl: "/forrestry-jekyll-demo" # the subpath of your site, e.g. /blog
url: "https://nathanstilwell.com"

# Build settings
markdown: kramdown

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
