---
label: default
hide_body: false
is_partial: false
fields:
- type: text
  name: title
  label: Page Title
  description: the title of the page
  default: page title
pages:
- guides/gnl-tao-te-ching-part-1.md
- guides/the-way.md
